---
runtimeobjectsgroupings:
  ConfigMap:
    - ConfigMap.blackduck.blackduck-config
    - ConfigMap.blackduck.blackduck-db-config
  Secrets:
    - Secret.blackduck.blackduck-upload-cache
    - Secret.blackduck.blackduck-db-creds
  InitJob:
    - ConfigMap.blackduck.postgres-init-config
    - Job.blackduck.blackduck-init-postgres
  Postgres:
    - ReplicationController.blackduck.blackduck-postgres
    - Service.blackduck.blackduck-postgres
  EverythingElse:
    - ReplicationController.blackduck.blackduck-registration
    - ReplicationController.blackduck.blackduck-scan
    - ReplicationController.blackduck.blackduck-webapp-logstash
    - Service.blackduck.authentication
    - ReplicationController.blackduck.blackduck-cfssl
    - Service.blackduck.blackduck-scan
    - Secret.blackduck.blackduck-webserver-certificate
    - ReplicationController.blackduck.blackduck-webserver
    - ReplicationController.blackduck.blackduck-jobrunner
    - Service.blackduck.blackduck-cfssl
    - Service.blackduck.blackduck-documentation
    - Service.blackduck.blackduck-registration
    - Service.blackduck.webapp
    - Service.blackduck.blackduck-logstash
    - ReplicationController.blackduck.blackduck-documentation
    - ReplicationController.blackduck.blackduck-zookeeper
    - ReplicationController.blackduck.blackduck-authentication
    - ReplicationController.blackduck.blackduck-uploadcache
    - Service.blackduck.blackduck-webserver
    - Service.blackduck.blackduck-zookeeper
    - Service.blackduck.uploadcache

runtimeobjectdependencies:
  - obj: EverythingElse
    isdependenton: ConfigMap
  - obj: EverythingElse
    isdependenton: Secrets
  - obj: EverythingElse
    isdependenton: Postgres
  - obj: EverythingElse
    isdependenton: InitJob
  - obj: InitJob
    isdependenton: Postgres
  - obj: Postgres
    isdependenton: ConfigMap
  - obj: Postgres
    isdependenton: Secrets
---

